client_secret: YiSBm5Hzzl9AadRQjLcHymN2WoZTR6hk
debug: false
disable_auto_update: true
disable_command_execute: false
disable_force_update: true
disable_nat: false
disable_send_query: false
gpu: false
insecure_tls: false
ip_report_period: 1800
report_delay: 1
server: ip.086571.xyz:8008
skip_connection_count: false
skip_procs_count: false
temperature: false
tls: false
use_gitee_to_upgrade: false
use_ipv6_country_code: false
uuid: 3e8903e6-ef39-488c-aaf2-1f7853f1fe2c
